# Generated by Django 5.2.5 on 2025-09-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='decs',
            new_name='desc',
        ),
    ]
